##
# Customer Support Agent Scenario
#
# @file
# @version 0.1

run:
	poetry run streamlit run app.py

simulate-baseline:
	poetry run python chatbot.py baseline-sonnet-and-sonnet

simulate-comparison:
	poetry run python chatbot.py comparison-sonnet-and-sonnet

# end
